/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in typical projects and is committed here
// so type checking works before the first local dev run.
