"use client";
import { useMemo, useState } from "react";
import { formatNumber, shortId } from "../../../_components/format";
export type ParcelRow = { id: string; x: number; y: number; soil: number; water: number; marketAccess: number; risk: number; quality: number; ownerId: string | null; ownerPlayerId: string | null };
export function ParcelMap({ parcels }: { parcels: ParcelRow[] }) {
  const [selected, setSelected] = useState<ParcelRow | null>(null);
  const maxQuality = Math.max(...parcels.map((p) => p.quality), 1);
  const byCoord = useMemo(() => new Map(parcels.map((p) => [`${p.x}:${p.y}`, p])), [parcels]);
  return <div className="grid gap-6 lg:grid-cols-[auto_1fr]"><div className="grid grid-cols-10 gap-1">{Array.from({ length: 100 }).map((_, i) => { const x = i % 10; const y = Math.floor(i / 10); const parcel = byCoord.get(`${x}:${y}`); const intensity = parcel ? parcel.quality / maxQuality : 0; return <button key={i} title={`${x},${y}`} onClick={() => parcel && setSelected(parcel)} className="h-10 w-10 rounded border border-white text-[10px] font-semibold text-slate-950" style={{ backgroundColor: `rgba(37, 99, 235, ${0.12 + intensity * 0.78})` }}>{parcel ? formatNumber(parcel.quality, 1) : "—"}</button>; })}</div><div className="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm"><h3 className="font-semibold text-slate-950">Selected parcel</h3>{selected ? <dl className="mt-3 grid grid-cols-2 gap-3"><dt className="text-slate-500">Coordinates</dt><dd>{selected.x}, {selected.y}</dd><dt className="text-slate-500">Quality</dt><dd>{formatNumber(selected.quality, 4)}</dd><dt className="text-slate-500">Soil</dt><dd>{formatNumber(selected.soil, 4)}</dd><dt className="text-slate-500">Water</dt><dd>{formatNumber(selected.water, 4)}</dd><dt className="text-slate-500">Market access</dt><dd>{formatNumber(selected.marketAccess, 4)}</dd><dt className="text-slate-500">Risk</dt><dd>{formatNumber(selected.risk, 4)}</dd><dt className="text-slate-500">Owner</dt><dd>{shortId(selected.ownerPlayerId ?? selected.ownerId)}</dd></dl> : <p className="mt-2 text-slate-600">Click a parcel to inspect quality, attributes, and owner.</p>}</div></div>;
}
